name: ace05_event
path: data/oneie/ace05-EN
data_class: OneIEEvent
split:
  train: train.oneie.json
  val: dev.oneie.json
  test: test.oneie.json
language: en
new_list:
 - condemn
 - pass away
 - go out of business
 - end
 - encounter
 - carry
 - separate
 - attend the trial
 - perform
 - remittance
 - begin
 - prosecute
delete_list: 
mapper:
  Business:Declare-Bankruptcy: go out of business
  Business:End-Org: end organization
  Business:Merge-Org: merge organization
  Business:Start-Org: start organization
  Conflict:Attack: attack 
  Conflict:Demonstrate: demonstrate  
  Contact:Meet: encounter
  Contact:Phone-Write: phone write  
  Justice:Acquit: acquit
  Justice:Appeal: appeal
  Justice:Arrest-Jail: arrest jail
  Justice:Charge-Indict: prosecute
  Justice:Convict: convict
  Justice:Execute: perform 
  Justice:Extradite: extradite
  Justice:Fine: fine  
  Justice:Pardon: pardon
  Justice:Release-Parole: release parole 
  Justice:Sentence: condemn
  Justice:Sue: sue  
  Justice:Trial-Hearing: attend the trial 
  Life:Be-Born: be born  
  Life:Die: pass away
  Life:Divorce: separate
  Life:Injure: injure
  Life:Marry: marry
  Movement:Transport: carry
  Personnel:Elect: elect
  Personnel:End-Position: end
  Personnel:Nominate: nominate
  Personnel:Start-Position: begin
  Transaction:Transfer-Money: remittance
  Transaction:Transfer-Ownership: transfer ownership
  FAC: facility
  GPE: geographical social political
  LOC: location
  ORG: organization
  PER: person
  VEH: vehicle
  WEA: weapon
  ORG-AFF: organization affiliation
  GEN-AFF: general affiliation
  PHYS: physical
  PART-WHOLE: part whole
  PER-SOC: personal social
  ART: agent artifact
  Defendant: defendant
  Prosecutor: prosecutor
  Person: person
  Origin: origin
  Buyer: buyer
  Plaintiff: plaintiff
  Victim: victim
  Org: organization
  Adjudicator: adjudicator
  Seller: seller
  Beneficiary: beneficiary
  Giver: giver
  Target: target
  Agent: agent
  Instrument: instrument
  Vehicle: vehicle
  Entity: entity
  Destination: destination
  Recipient: recipient
  Attacker: attacker
  Artifact: artifact
  Place: place




  