name: NYT
path: data/NYT-multi
data_class: JointER
split:
  train: train.json
  val: dev.json
  test: test.json
language: en
new_list:
 - administrative divisions
 - country
 - founders
 - neighborhood of
 - place of death
 - teams
delete_list:
mapper:
  /business/company/advisors: advisors
  /business/company/founders: founders
  /business/company/industry: industry
  /business/company/major_shareholders: business
  /business/company/place_founded: place founded
  /business/company_shareholder/major_shareholder_of: major shareholder of
  /business/person/company: company
  /location/administrative_division/country: country
  /location/country/administrative_divisions: administrative divisions
  /location/country/capital: location
  /location/location/contains: contains
  /location/neighborhood/neighborhood_of: neighborhood of
  /people/deceased_person/place_of_death: place of death
  /people/ethnicity/geographic_distribution: geographic distribution
  /people/ethnicity/people: people group
  /people/person/children: children
  /people/person/ethnicity: ethnicity
  /people/person/nationality: people
  /people/person/place_lived: people
  /people/person/place_of_birth: people
  /people/person/profession: profession
  /people/person/religion: religion
  /sports/sports_team/location: sports
  /sports/sports_team_location/teams: teams
  ORGANIZATION: organization
  LOCATION: location
  PERSON: person